name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  GO_VERSION: 1.17

jobs:
  lint:
    name: golangci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
  create-release-pr:
    runs-on: ubuntu-latest
    needs:
      - lint
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      sha: ${{ steps.release.outputs.sha }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
    steps:
      # Checkout and test
      - uses: actions/checkout@v2
      # Create a release, or update the release PR
      - uses: GoogleCloudPlatform/release-please-action@v3.1.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          bump-minor-pre-major: true
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - create-release-pr
    if: ${{ needs.create-release-pr.outputs.release_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref:  ${{ needs.create-release-pr.outputs.tag_name }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
